/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#004328',
        'surface-bright': '#faf8ff',
        'primary-container': '#0d5c3a',
        'on-error-container': '#93000a',
        'surface-container-high': '#e2e7ff',
        'primary-fixed': '#a9f3c5',
        'on-secondary-container': '#00714d',
        'on-secondary-fixed': '#002113',
        'surface-container-highest': '#dae2fd',
        'tertiary-fixed-dim': '#a8cfbc',
        'surface-tint': '#226b47',
        'on-primary-container': '#8ad2a7',
        'on-secondary-fixed-variant': '#005236',
        'on-surface-variant': '#404942',
        'on-primary-fixed-variant': '#005232',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#8ed6aa',
        'surface': '#faf8ff',
        'inverse-primary': '#8ed6aa',
        'on-error': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#283044',
        'on-tertiary': '#ffffff',
        'on-background': '#131b2e',
        'background': '#faf8ff',
        'outline': '#707971',
        'error-container': '#ffdad6',
        'tertiary-container': '#335748',
        'on-secondary': '#ffffff',
        'tertiary': '#1b4031',
        'on-surface': '#131b2e',
        'error': '#ba1a1a',
        'tertiary-fixed': '#c3ecd7',
        'on-tertiary-fixed': '#002115',
        'inverse-on-surface': '#eef0ff',
        'surface-variant': '#dae2fd',
        'on-tertiary-fixed-variant': '#294e3f',
        'secondary-fixed-dim': '#4edea3',
        'secondary': '#006c49',
        'surface-dim': '#d2d9f4',
        'surface-container-low': '#f2f3ff',
        'secondary-fixed': '#6ffbbe',
        'on-primary-fixed': '#002111',
        'on-tertiary-container': '#a4cbb8',
        'secondary-container': '#6cf8bb',
        'surface-container': '#eaedff',
        'outline-variant': '#bfc9c0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-xs': '0.25rem',
        gutter: '1rem',
        'space-xl': '2rem',
        margin: '1rem',
        'margin-desktop': '2rem',
        'gutter-desktop': '1.5rem',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'body-sm': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-xl-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        'headline-sm': ['Plus Jakarta Sans'],
        display: ['Plus Jakarta Sans'],
        'display-mobile': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', fontWeight: '700' }],
        'headline-xl': ['36px', { lineHeight: '44px', fontWeight: '800' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-xl-mobile': ['28px', { lineHeight: '36px', fontWeight: '800' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        display: ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};